### ISSUE TITLE
Feature request: handle NaN

### ISSUE THREAD

**Issue by bersbersbers** [python-humanize/humanize#62]
### What did you do?

```python
import humanize, math
humanize.metric(math.nan)
```

### What did you expect to happen?

`"NaN"`

### What actually happened?

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bers\\.pyenv-win-venv\envs\project\lib\site-packages\humanize\number.py", line 519, in metric
    exponent = int(math.floor(math.log10(abs(value)))) if value != 0 else 0
ValueError: cannot convert float NaN to integer

**Comment by bersbersbers** [comment]
(For the record, I did not *actually* do `humanize.metric(math.nan)`, I just happened to come across a NaN value.)

**Comment by bersbersbers** [comment]
It would also make sense to handle this in one common location for +/-Inf and all other functions failing on NaN, such as `humanize.scientific(math.nan)` or `humanize.fractional(math.nan)`.
